services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - app_data:/app/user-scripts
    develop:
      watch:
        - action: rebuild
          path: ./web
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "8000:8000"
volumes:
  app_data:
